import { Poppins } from 'next/font/google'
import '@/styles/globals.css'
import { Footer, Header } from '@/components/common'

const poppins = Poppins({
	subsets: ['latin'],
	weight: ['400', '500', '600', '700'],
	variable: '--font-poppins',
	display: 'swap',
})

export const metadata = {
	title: 'KinoTime',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='uz'>
			<body className={poppins.variable}>
				<Header />
				{children}
				<Footer />
			</body>
		</html>
	)
}
